openapi: 3.0.3
info:
  title: TA2 API
  description: xxx
  version: 1.0.0
  contact:
    name: Rafael Urben
    email: github@rafaelurben.ch
    url: https://www.rafaelurben.ch
servers:
  - url: 'http://localhost:8181/api/v1'
  - url: 'http://localhost:8182/api/v1'
paths:

components:
  parameters:

  schemas:

