name: Run full analysis

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn compile package --batch-mode --no-transfer-progress

      - id: docker-compose
        name: Build and start docker containers and wait for them to be ready
        run: docker compose -f docker-compose.yaml --profile "*" up -d --wait --build --quiet-pull

      - name: (On failure) Log docker container status
        if: failure() && steps.docker-compose.conclusion == 'failure'
        run: |
          echo "Docker container status:"
          docker compose -f docker-compose.yaml --profile "*" ps --all
          echo "Health status of impl1mongodb"
          docker inspect --format "{{json .State.Health }}" impl1mongodb
          echo "Health status of impl2kurrentdb"
          docker inspect --format "{{json .State.Health }}" impl2kurrentdb
          echo "Logs from impl1mongodb"
          docker logs impl1mongodb --tail 100
          echo "Logs from impl2kurrentdb"
          docker logs impl2kurrentdb --tail 100

      - name: Run tests
        run: mvn -f testing-client/pom.xml clean compile exec:java

      - name: Stop and remove docker containers and volumes
        run: docker compose -f docker-compose.yaml --profile "*" down --volumes

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        run: python -m pip install -r stats/requirements.txt

      - name: Run analysis
        run: python stats/analyze.py

      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: stats/results
