name: Run full analysis

on:
  workflow_dispatch:
    inputs:
      test_runs:
        description: 'Number of times to run tests'
        required: true
        default: '1'
        type: choice
        options:
          - "1"
          - "2"
          - "3"

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn compile package --batch-mode --no-transfer-progress

      - id: docker-compose
        name: Build and start docker containers and wait for them to be ready
        run: docker compose -f docker-compose.yaml --profile "*" up -d --wait --build --quiet-pull

      - name: (On failure) Log docker container status
        if: failure() && steps.docker-compose.conclusion == 'failure'
        run: |
          echo "Docker container status:"
          docker compose -f docker-compose.yaml --profile "*" ps --all
          echo "Health status of impl1mongodb"
          docker inspect --format "{{json .State.Health }}" impl1mongodb
          echo "Health status of impl2kurrentdb"
          docker inspect --format "{{json .State.Health }}" impl2kurrentdb
          echo "Logs from impl1mongodb"
          docker logs impl1mongodb --tail 100
          echo "Logs from impl2kurrentdb"
          docker logs impl2kurrentdb --tail 100

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        run: python -m pip install -r stats/requirements.txt

      - name: Run tests and upload test data (1)
        uses: ./.github/actions/run-tests-and-analyze
        with:
          suffix: '1'

      - name: Run tests and upload test data (2)
        uses: ./.github/actions/run-tests-and-analyze
        with:
          suffix: '2'
        if: ${{ github.event.inputs.test_runs == '2' || github.event.inputs.test_runs == '3' }}

      - name: Run tests and upload test data (3)
        uses: ./.github/actions/run-tests-and-analyze
        with:
          suffix: '3'
        if: ${{ github.event.inputs.test_runs == '3' }}

      - name: Stop and remove docker containers and volumes
        run: docker compose -f docker-compose.yaml --profile "*" down --volumes
